# 横断研究  {#crosssectional-intro}

## キーワード  {#sec-crosssectional-keyword}

コホート研究 (cohort study) には、いくつかの種類があります。

まず、ある１時点での調査を行うことを横断研究 (cross-sectional study)、複数の時点で調査を行うことを縦断研究 (longitudinal study) と言います。

横断研究では、通常、ある疾患 (ここではフレイル) の有病率や、さまざまな属性との関連を調べます。この属性を、RCT での介入に対して、コホート研究では暴露 (exposure) と言うこともあります。

横断研究では、統計手法としては、ロジスティック回帰 (logistic regression) がよく用いられます。これは、単一のアウトカムに対して、複数の属性を共変量 (covariate) として解析し、関連 (association) があるかどうかを調査します。最終的には、共変量ごとにオッズ比が得られます。

ロジスティック回帰を理解するためには、まずオッズ比とリスク比を理解する必要があります。

まず、以下のオッズ比とリスク比を計算してみましょう。


|   | 疾患あり | 疾患なし | 合計 |
| - | -------- | -------- | ---- |
| 暴露あり | 20人 | 80人 | 100人 | 
| 暴露なし | 10人 | 90人 | 100人 | 
| 合計 | 30人 | 170人 | 200人 | 


リスク比 = $\dfrac{ \dfrac{20}{100} }{ \dfrac{10}{100} } = 2.00$

リスク比は簡単に理解できます。「暴露ありのほうが、暴露なしよりも 2.00 倍の疾患リスクがある」と解釈することができます。

オッズ比 = $\dfrac{ \dfrac{20}{80} }{ \dfrac{10}{90} } = 2.25$

このように、オッズ比はリスク比に近いけれども、ちょっと大袈裟にでる傾向があります。[^crosssectional-or]

[^crosssectional-or]: オッズ比は、1 より大きい場合はリスク比よりも大きく、1 より小さい場合はリスク比より小さく出ます。

このため、オッズ比 2.25 は、「暴露ありのほうが、暴露なしよりも 2.25倍の疾患リスクがある」と解釈することはできません [@tajeu2012misuse; @holcomb2001odd]。

なお、全体の有病率が低くなるほどオッズ比はリスク比に近づき、10% 以下ではほぼリスク比に近似できます。

|   | 疾患あり | 疾患なし | 合計 |
| - | -------- | -------- | ---- |
| 暴露あり | 2人 | 98人 | 100人 | 
| 暴露なし | 1人 | 99人 | 100人 | 
| 合計 | 3人 | 197人 | 200人 | 

リスク比は 2.00 のままですが、オッズ比は 2.02 になります。

上の表では、要因が一つ (暴露) だけでした。これを、複数に拡張したものがロジスティック回帰になります。また、2 値変数だけではなく数値も使用することができます。

横断研究では多くの場合、以下の調査を行います。

- 有病率を求める
- リスク因子のオッズ比を求める

これで全てではありません。例えば、Chapter 2 でみた Fried LP (2001) もコホート研究の一種です。

コホート研究の論文のガイドラインは、STROBE 宣言です。

## 有病率と関連要因の調査

ここでは多くの場合、以下の調査を行う横断研究について解説します。

- 有病率を求める
- リスク因子のオッズ比を求める

リスク因子のオッズ比を調査するためには、多変数ロジスティック回帰を行います。[^crosssectional-multivariable]

[^crosssectional-multivariable]: 説明変数が複数あるときに多変数 (multivariable)、アウトカム変数が複数あるときに多変量 (multivariate) とする [@hidalgo2013multivariate]

説明変数は、仮説や先行研究から決定することが多いようです。

論文の例: Liu W, Puts M, Jian F et al. (2020) Physical frailty and its associated factors among elderly nursing home residents in China. *BMC Geriatrics*, 20(1), 1-9.

