# レター  {#critical-letter}

## 批判的吟味 (Critical Reading)

臨床論文を読む際は、批判的に読む姿勢が必要になります。ここでは、このような姿勢・方法論を批判的吟味 (Critical Reading) といいます。

批判的吟味では、臨床論文に書かれたことをよく吟味しながら読みます。「批判的」というのは、必ずしも「否定的」という意味ではありません。


誹謗中傷ではなく、論文がより良くなる建設的な質問・コメント

    Introduction については聞かない (理由: 著者の意見というよりは、すでに受け入れられている他者の論文)
    Limitations に書かれていることは指摘しない


## 自動翻訳

DeepL: https://www.deepl.com/

みらい翻訳: https://miraitranslate.com/trial/

例文: バーセルインデックスが有意に改善することが明らかになった。

DeepL: A significant improvement in the bar-cell index was found.

みらい: It was clarified that the Barthel index was significantly improved.

## 文法チェック

DeepL Write: https://www.deepl.com/ja/write#en/

Grammarly: https://www.grammarly.com/

## 書き換えツール

QuillBot: https://quillbot.com/

Language Tool: https://languagetool.org/

例文: It was clarified that the Barthel index was significantly improved.

Quillbot: (Standard) It was made clear that there was a notable improvement in the Barthel index.

Language Tool: (Formal) It was clarified that the Barthel index had been significantly improved.

