# ランダム化比較試験  {#rct-intro}

## キーワード  {#sec-rct-keyword}

ランダム化比較試験 (randomised controlled trial, RCT) は、「ランダム化」 (randomisation) という手法で介入群と対照群を設定する臨床試験です。

ところが、ランダム化とは何か？と聞かれると、意外と答えられないものです。また、論文ではランダム化の方法まで報告されていることは少ないようです。ランダム化は、どのような目的で行うのでしょうか？

ランダム化の目的は、介入群と対照群を均質にすることにあります。例えば、年齢や性別が影響を及ぼす場合、100人をランダム化する場合は、両群の平均年齢と男女比がほぼ同じになるように分けます。このような、影響を及ぼす誤差を系統誤差 (systematic error) といいます。一方、「ほぼ」の部分は偶然誤差 (random error) になります。

おや、偶然誤差の「偶然」は、英語では random ですね。つまり、これがランダム化ということです。例えば、ランダム化して平均年齢が 70.4 才と 70.5 才になったとしたら、その差 0.1 は偶然誤差と言えます。

振り分けを「ランダムに」行うのではなく、「ランダムになるように」振り分けを意図的に行うことです。

ランダム化の目的は、医師国家試験に数回出題されたことがあります。

::: {.callout-note}
## 医師国家試験 第110回 B 22

ランダム化比較試験〈無作為化比較対照試験〉においてランダム割付を実施する目的はどれか。

a 治療中断の防止

b 偶然誤差の制御

c 治療内容の盲検化

d 比較群間の均質性の向上

e 患者の試験への参加率の上昇
:::

ランダム化の目的は、正解は d となります。b については、「系統誤差を制御」が正しく、偶然誤差はランダム化でも残ります。1

1 選択肢 c にある「盲検化」とは何か？

介入 (intervention) と対照 (control) の比較を行います。動物実験の場合、対照を Sham ということもあります。

::: {.callout-note}
## 医師国家試験 第118回 B 09

ランダム化比較試験〈RCT〉で正しいのはどれか。

a 観察研究である。

b 外的妥当性が高い研究である。

c 未測定の交絡因子に対応できない。

d 有病率の低い疾患の研究に適している。

e 症例対照研究よりエビデンスレベルが高い。
:::

RCT は、介入前をベースライン (baseline) と言います。また介入が終了した後に効果が持続するかどうかを見るために、3ヶ月や 1 年など追跡 (follow-up) 調査することもよくあります。調査時点を、介入前 (T0)、介入直後 (T1)、追跡 (T2) などと表現することもあります。

解析対象については、Intention-to-treat 解析や Per protcol 解析が行われることがあります。Intention-to-treat は、治療の意図という意味で、実際の治療ではなく当初の治療を指します。一方、Per protocol は実際に行われた治療を指します。この二つの単語については、日本語訳はされないことの方が多いようです。RCT では通常、per protocol よりも ITT の方が望ましいとされています。

AMA Manual of Style では、以下のように定義しています。

**Intention-to-treat (ITT) analysis** is the preferred way to report randomized trial results. Final results are based on analysis of data from all the participants who were originally randomly assigned, whether or not they completed the trial.

A **per-protocol analysis** reports a study’s results by the treatment received and not by the group into which the participants were randomly assigned.

[@ama2020ama, p. 988]

::: {.callout-note}
## 第110回 B 13

治療 A と治療 B との比較を目的としたランダム化比較試験〈無作為化比較対照試験〉を行った。割り付けと実際の治療人数の表を示す。

| | 治療 A を実際に行った | 治療 B を実際に行った | 治療開始前 に死亡した | 合計 |
| - | - | - | - | - |
治療A割付 | 110人 | 15人 | 4人 | 129人 | 
治療B割付 | 6人 | 115人 | 0人 | 121人 | 
合計 | 116人 | 130人 | 4人 | 250人 | 

intention to treat〈ITT〉で２つの治療を比較するときに、治療 A と治療 B の組み合わせで正しいのはどれか。
:::

ITT ですので、「割付」を見れば良いことになります。割り付けられたのは、治療 A が 129 人、治療 B が 121 人です。これが正解になります。

ただし、RCT においては、実際には死亡した人の After のデータがない可能性があります。実際、この問題でも治療Aは125人という選択肢があり、そこで悩んだ人もいたようです。

では、Per protocol 解析だとすると何人でしょうか？治療 A に割付られ、実際に治療 A を行った 110 人と、治療 B の 115 人となります。

ここまで見たように、RCT の強みは、実験に参加した患者 (または参加者) については妥当性が高いと言えます。これを内的妥当性 (internal validity) と言います。対象者以外に拡張する場合は外的妥当性 (external validity) や一般化可能性 (generalisability)と言います。

::: {.callout-note}
## 医師国家試験 第115回 B 06

ランダム化比較試験〈RCT〉について正しいのはどれか。

a 内的妥当性が高い。

b 二重盲検を要件とする。

c 第１相臨床試験で用いられる。

d メタ分析〈メタアナリシス〉の一種である。

e 観察研究に比べて交絡因子の影響が大きい。
:::


RCT の特徴は、内的妥当性の高さなので、a が正解となります。

選択肢 e に、交絡因子 (confounding factor) という言葉があります。交絡因子は系統誤差の原因の一つですので、RCT ではむしろ影響が少なくなります。交絡因子は、統計学的には「調整」(adjustment) をする必要が出てきます。

confounding variable: variable that can cause or prevent the outcome of interest, is not an intermediate variable, and is associated with the factor under investivgation. Unless it is possible to adjust for confounding variables their effects cannot be distinguished from those of the factors being studied. … [@ama2020ama, p. 1028]

統計手法としては、繰り返しのある二元配置分散分析 (two-way repeated measures ANOVA) や混合モデル (mixed model) といった解析方法を使います。

RCT には、倫理的な課題があります。それは、参加者の多くは治療を期待しているのにも関わらず、治療をしない対照群に割り当てられる可能性がある点です。この観点から、サンプルサイズ (sample size) は小さい方が好ましくなります。一方で、効果推定のためにはサンプルサイズが大きい方が好ましいです。このため、予備試験 (pilot study) を実施し、サンプルサイズを推定することがあります。なお、サンプルサイズは症例数ということもあります。



::: {.callout-note}
## 医師国家試験 第114回 E 17

ランダム化比較試験〈RCT〉について正しいのはどれか。

a 二重盲検は必須である。

b プラセボは現在では使用が禁止されている。

c ランダム割付は症例数を少なくするために行われる。

d 症例数の設定のためには治療効果の推定が必要である。

e Intention to treat〈ITT〉による解析は実際に行った治療に基づいて行われる。

:::

正解は、d となります。

RCT の論文のガイドラインは、CONSORT 宣言です。

論文の例: Siramolpiwat S, Limthanetkul N, Pornthisarn B, Vilaichone RK, Chonprasertsuk S, Bhanthumkomol P, ... & Issariyakulkarn N (2023). Branched-chain amino acids supplementation improves liver frailty index in frail compensated cirrhotic patients: a randomized controlled trial. BMC gastroenterology, 23(1), 154.

Teh R, Barnett D, Edlin R, Kerse N, Waters DL, Hale L, ... & Pillai A (2022). Effectiveness of a complex intervention of group-based nutrition and physical activity to prevent frailty in pre-frail older adults (SUPER): A randomised controlled trial. The Lancet Healthy Longevity, 3(8), e519-e530.
